services:
  - type: web
    name: weather-skin-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_enhanced:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEATHER_API_KEY
        sync: false
    autoDeploy: true
